enum UserRole { player, managerTeam, referee, adminField }
enum Position { por, def, med, del }
enum VerificationStatus { verified, pending, rejected }
enum MatchStatus { scheduled, live, finished, suspended }
enum MatchEventType { goal, assist, yellowCard, redCard, substitution, matchStarted, matchEnded }

Position positionFromString(String v) => Position.values.firstWhere((e) => e.name.toUpperCase() == v.toUpperCase(), orElse: () => Position.del);
String positionLabel(Position p) => switch (p) { Position.por => 'Portero', Position.def => 'Defensa', Position.med => 'Medio', Position.del => 'Delantero' };

class PlayerStats { int matchesPlayed, goals, assists, yellowCards, redCards; double rating;
  PlayerStats({this.matchesPlayed=0,this.goals=0,this.assists=0,this.yellowCards=0,this.redCards=0,this.rating=0});
  Map<String,dynamic> toJson()=>{'matchesPlayed':matchesPlayed,'goals':goals,'assists':assists,'yellowCards':yellowCards,'redCards':redCards,'rating':rating};
  factory PlayerStats.fromJson(Map<String,dynamic> j)=>PlayerStats(matchesPlayed:j['matchesPlayed']??0,goals:j['goals']??0,assists:j['assists']??0,yellowCards:j['yellowCards']??0,redCards:j['redCards']??0,rating:(j['rating']??0).toDouble());
}
class Player { String id, fullName, photoUrl, teamId, teamName; Position position; int dorsal; double overallRating; VerificationStatus verificationStatus; PlayerStats stats;
  Player({required this.id,required this.fullName,required this.position,required this.dorsal,required this.photoUrl,required this.overallRating,required this.verificationStatus,required this.teamId,required this.teamName,required this.stats});
  Map<String,dynamic> toJson()=>{'id':id,'fullName':fullName,'position':position.name,'dorsal':dorsal,'photoUrl':photoUrl,'overallRating':overallRating,'verificationStatus':verificationStatus.name,'teamId':teamId,'teamName':teamName,'stats':stats.toJson()};
  factory Player.fromJson(Map<String,dynamic> j)=>Player(id:j['id'],fullName:j['fullName'],position:positionFromString(j['position']),dorsal:j['dorsal']??10,photoUrl:j['photoUrl']??'',overallRating:(j['overallRating']??0).toDouble(),verificationStatus:VerificationStatus.values.firstWhere((e)=>e.name==j['verificationStatus'],orElse:()=>VerificationStatus.verified),teamId:j['teamId']??'',teamName:j['teamName']??'',stats:PlayerStats.fromJson(Map<String,dynamic>.from(j['stats']??{})));
}
class Field { String id,name,logoUrl,photoUrl,location,description,adminId; int activeLeaguesCount; Field({required this.id,required this.name,required this.logoUrl,required this.photoUrl,required this.location,required this.description,required this.adminId,required this.activeLeaguesCount}); }
class League { String id,fieldId,name,season,category,rules; League({required this.id,required this.fieldId,required this.name,required this.season,required this.category,required this.rules}); }
class Team { String id,leagueId,fieldId,name,crestUrl,managerId; List<String> colors; int? positionInTable; Team({required this.id,required this.leagueId,required this.fieldId,required this.name,required this.crestUrl,required this.colors,required this.managerId,this.positionInTable}); Map<String,dynamic> toJson()=>{'id':id,'leagueId':leagueId,'fieldId':fieldId,'name':name,'crestUrl':crestUrl,'colors':colors,'managerId':managerId,'positionInTable':positionInTable}; factory Team.fromJson(Map<String,dynamic> j)=>Team(id:j['id'],leagueId:j['leagueId'],fieldId:j['fieldId'],name:j['name'],crestUrl:j['crestUrl']??'',colors:List<String>.from(j['colors']??[]),managerId:j['managerId']??'',positionInTable:j['positionInTable']); }
class Match { String id,leagueId,fieldId,homeTeamId,homeTeamName,homeTeamCrest,awayTeamId,awayTeamName,awayTeamCrest,date,time,refereeId,refereeName,venueName; int matchday,homeScore,awayScore; MatchStatus status; Match({required this.id,required this.leagueId,required this.fieldId,required this.homeTeamId,required this.homeTeamName,required this.homeTeamCrest,required this.awayTeamId,required this.awayTeamName,required this.awayTeamCrest,required this.date,required this.time,required this.matchday,required this.status,required this.homeScore,required this.awayScore,required this.refereeId,required this.refereeName,required this.venueName}); }
class Standing { String id,leagueId,teamId,teamName,crestUrl; int played,won,drawn,lost,goalsFor,goalsAgainst,goalDifference,points; Standing({required this.id,required this.leagueId,required this.teamId,required this.teamName,required this.crestUrl,required this.played,required this.won,required this.drawn,required this.lost,required this.goalsFor,required this.goalsAgainst,required this.goalDifference,required this.points}); }
class LineupPlayer { String playerId,name; int dorsal; Position position; bool isStarter; double x,y; LineupPlayer({required this.playerId,required this.name,required this.dorsal,required this.position,required this.isStarter,required this.x,required this.y}); }
class TeamLineup { String matchId,teamId,formation; List<LineupPlayer> players; TeamLineup({required this.matchId,required this.teamId,required this.formation,required this.players}); }
class MatchEvent { String id,matchId,teamId,playerId,playerName,refereeId; MatchEventType type; int minute; String? secondaryPlayerId,secondaryPlayerName; int timestamp; MatchEvent({required this.id,required this.matchId,required this.type,required this.teamId,required this.playerId,required this.playerName,required this.minute,required this.refereeId,required this.timestamp,this.secondaryPlayerId,this.secondaryPlayerName}); }
